{{- if .Values.consumerRegistration.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.consumerRegistration.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: maestro-consumer-registration
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
