/*
maestro Service API

maestro Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ResourceAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceAllOf{}

// ResourceAllOf struct for ResourceAllOf
type ResourceAllOf struct {
	ConsumerId      *string                `json:"consumer_id,omitempty"`
	Version         *int32                 `json:"version,omitempty"`
	ObservedVersion *int32                 `json:"observed_version,omitempty"`
	CreatedAt       *time.Time             `json:"created_at,omitempty"`
	UpdatedAt       *time.Time             `json:"updated_at,omitempty"`
	Manifest        map[string]interface{} `json:"manifest,omitempty"`
	Status          map[string]interface{} `json:"status,omitempty"`
}

// NewResourceAllOf instantiates a new ResourceAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceAllOf() *ResourceAllOf {
	this := ResourceAllOf{}
	return &this
}

// NewResourceAllOfWithDefaults instantiates a new ResourceAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceAllOfWithDefaults() *ResourceAllOf {
	this := ResourceAllOf{}
	return &this
}

// GetConsumerId returns the ConsumerId field value if set, zero value otherwise.
func (o *ResourceAllOf) GetConsumerId() string {
	if o == nil || IsNil(o.ConsumerId) {
		var ret string
		return ret
	}
	return *o.ConsumerId
}

// GetConsumerIdOk returns a tuple with the ConsumerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceAllOf) GetConsumerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConsumerId) {
		return nil, false
	}
	return o.ConsumerId, true
}

// HasConsumerId returns a boolean if a field has been set.
func (o *ResourceAllOf) HasConsumerId() bool {
	if o != nil && !IsNil(o.ConsumerId) {
		return true
	}

	return false
}

// SetConsumerId gets a reference to the given string and assigns it to the ConsumerId field.
func (o *ResourceAllOf) SetConsumerId(v string) {
	o.ConsumerId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ResourceAllOf) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceAllOf) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ResourceAllOf) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *ResourceAllOf) SetVersion(v int32) {
	o.Version = &v
}

// GetObservedVersion returns the ObservedVersion field value if set, zero value otherwise.
func (o *ResourceAllOf) GetObservedVersion() int32 {
	if o == nil || IsNil(o.ObservedVersion) {
		var ret int32
		return ret
	}
	return *o.ObservedVersion
}

// GetObservedVersionOk returns a tuple with the ObservedVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceAllOf) GetObservedVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.ObservedVersion) {
		return nil, false
	}
	return o.ObservedVersion, true
}

// HasObservedVersion returns a boolean if a field has been set.
func (o *ResourceAllOf) HasObservedVersion() bool {
	if o != nil && !IsNil(o.ObservedVersion) {
		return true
	}

	return false
}

// SetObservedVersion gets a reference to the given int32 and assigns it to the ObservedVersion field.
func (o *ResourceAllOf) SetObservedVersion(v int32) {
	o.ObservedVersion = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ResourceAllOf) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceAllOf) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ResourceAllOf) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ResourceAllOf) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ResourceAllOf) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceAllOf) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ResourceAllOf) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ResourceAllOf) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetManifest returns the Manifest field value if set, zero value otherwise.
func (o *ResourceAllOf) GetManifest() map[string]interface{} {
	if o == nil || IsNil(o.Manifest) {
		var ret map[string]interface{}
		return ret
	}
	return o.Manifest
}

// GetManifestOk returns a tuple with the Manifest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceAllOf) GetManifestOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Manifest) {
		return map[string]interface{}{}, false
	}
	return o.Manifest, true
}

// HasManifest returns a boolean if a field has been set.
func (o *ResourceAllOf) HasManifest() bool {
	if o != nil && !IsNil(o.Manifest) {
		return true
	}

	return false
}

// SetManifest gets a reference to the given map[string]interface{} and assigns it to the Manifest field.
func (o *ResourceAllOf) SetManifest(v map[string]interface{}) {
	o.Manifest = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResourceAllOf) GetStatus() map[string]interface{} {
	if o == nil || IsNil(o.Status) {
		var ret map[string]interface{}
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceAllOf) GetStatusOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Status) {
		return map[string]interface{}{}, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResourceAllOf) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given map[string]interface{} and assigns it to the Status field.
func (o *ResourceAllOf) SetStatus(v map[string]interface{}) {
	o.Status = v
}

func (o ResourceAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerId) {
		toSerialize["consumer_id"] = o.ConsumerId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.ObservedVersion) {
		toSerialize["observed_version"] = o.ObservedVersion
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Manifest) {
		toSerialize["manifest"] = o.Manifest
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResourceAllOf struct {
	value *ResourceAllOf
	isSet bool
}

func (v NullableResourceAllOf) Get() *ResourceAllOf {
	return v.value
}

func (v *NullableResourceAllOf) Set(val *ResourceAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceAllOf(val *ResourceAllOf) *NullableResourceAllOf {
	return &NullableResourceAllOf{value: val, isSet: true}
}

func (v NullableResourceAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
