/*
maestro Service API

maestro Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsumerListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerListAllOf{}

// ConsumerListAllOf struct for ConsumerListAllOf
type ConsumerListAllOf struct {
	Items []Consumer `json:"items,omitempty"`
}

// NewConsumerListAllOf instantiates a new ConsumerListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerListAllOf() *ConsumerListAllOf {
	this := ConsumerListAllOf{}
	return &this
}

// NewConsumerListAllOfWithDefaults instantiates a new ConsumerListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerListAllOfWithDefaults() *ConsumerListAllOf {
	this := ConsumerListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ConsumerListAllOf) GetItems() []Consumer {
	if o == nil || IsNil(o.Items) {
		var ret []Consumer
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsumerListAllOf) GetItemsOk() ([]Consumer, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ConsumerListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Consumer and assigns it to the Items field.
func (o *ConsumerListAllOf) SetItems(v []Consumer) {
	o.Items = v
}

func (o ConsumerListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableConsumerListAllOf struct {
	value *ConsumerListAllOf
	isSet bool
}

func (v NullableConsumerListAllOf) Get() *ConsumerListAllOf {
	return v.value
}

func (v *NullableConsumerListAllOf) Set(val *ConsumerListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerListAllOf(val *ConsumerListAllOf) *NullableConsumerListAllOf {
	return &NullableConsumerListAllOf{value: val, isSet: true}
}

func (v NullableConsumerListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
