/*
maestro Service API

maestro Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResourceBundleList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceBundleList{}

// ResourceBundleList struct for ResourceBundleList
type ResourceBundleList struct {
	Kind  string           `json:"kind"`
	Page  int32            `json:"page"`
	Size  int32            `json:"size"`
	Total int32            `json:"total"`
	Items []ResourceBundle `json:"items"`
}

// NewResourceBundleList instantiates a new ResourceBundleList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceBundleList(kind string, page int32, size int32, total int32, items []ResourceBundle) *ResourceBundleList {
	this := ResourceBundleList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewResourceBundleListWithDefaults instantiates a new ResourceBundleList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceBundleListWithDefaults() *ResourceBundleList {
	this := ResourceBundleList{}
	return &this
}

// GetKind returns the Kind field value
func (o *ResourceBundleList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ResourceBundleList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ResourceBundleList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *ResourceBundleList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ResourceBundleList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ResourceBundleList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ResourceBundleList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ResourceBundleList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ResourceBundleList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ResourceBundleList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ResourceBundleList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ResourceBundleList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *ResourceBundleList) GetItems() []ResourceBundle {
	if o == nil {
		var ret []ResourceBundle
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ResourceBundleList) GetItemsOk() ([]ResourceBundle, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ResourceBundleList) SetItems(v []ResourceBundle) {
	o.Items = v
}

func (o ResourceBundleList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceBundleList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableResourceBundleList struct {
	value *ResourceBundleList
	isSet bool
}

func (v NullableResourceBundleList) Get() *ResourceBundleList {
	return v.value
}

func (v *NullableResourceBundleList) Set(val *ResourceBundleList) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceBundleList) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceBundleList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceBundleList(val *ResourceBundleList) *NullableResourceBundleList {
	return &NullableResourceBundleList{value: val, isSet: true}
}

func (v NullableResourceBundleList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceBundleList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
