---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Mosquitto mqtt broker for use with the maestro
    iconClass: icon-mosquitto
    openshift.io/display-name: Example Mosquitto MQTT Broker
    tags: mqtt,mosquitto
  name: maestro-mqtt
parameters:
  - name: MQTT_BROKER_NAME
    description: The name of the OpenShift Service exposed for the database.
    displayName: Database Service Name
    required: true
    value: maestro-mqtt

  - name: MQTT_IMAGE
    description: Mosquitto image (2.0.18 or latest).
    displayName: Mosquitto Image
    required: true
    value: "eclipse-mosquitto:2.0.18"

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: tcp://{.spec.clusterIP}:{.spec.ports[?(.name==\mosquitto\)].port}
      name: ${MQTT_BROKER_NAME}
    spec:
      ports:
      - name: mosquitto
        nodePort: 0
        protocol: TCP
        port: 1883
        targetPort: 1883
      selector:
        name: ${MQTT_BROKER_NAME}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${MQTT_BROKER_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${MQTT_BROKER_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: ${MQTT_BROKER_NAME}
        spec:
          serviceAccountName: maestro
          containers:
          - image: ${MQTT_IMAGE}
            imagePullPolicy: IfNotPresent
            name: mosquitto
            ports:
            - containerPort: 1883
              name: mosquitto
            volumeMounts:
            - name: mosquitto-persistent-storage
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          volumes:
          - name: mosquitto-persistent-storage
            emptyDir: {}
          - name: mosquitto-config
            configMap:
              name: ${MQTT_BROKER_NAME}
    status: {}

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${MQTT_BROKER_NAME}
    data:
      mosquitto.conf: |
        listener 1883 0.0.0.0
        allow_anonymous true
