---
apiVersion: v1
kind: Template
name: uhc-acct-mangr-routes
metadata:
  name: route

parameters:

- name: EXTERNAL_APPS_DOMAIN
  description: external apps domain for exposing route

objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: maestro
    labels:
      app: maestro
  spec:
    host: maestro.${EXTERNAL_APPS_DOMAIN}
    to:
      kind: Service
      name: maestro
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: maestro-grpc
    labels:
      app: maestro-grpc
  spec:
    host: maestro-grpc.${EXTERNAL_APPS_DOMAIN}
    to:
      kind: Service
      name: maestro-grpc
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
