---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: maestro-secrets
  annotations:
    description: "maestro Secrets"
parameters:

- name: DATABASE_HOST
  description: Hostname for the database server.

- name: DATABASE_PORT
  description: Port of the database server.

- name: DATABASE_NAME
  description: Name for the database in the server.

- name: DATABASE_USER
  description: User for the database server.

- name: DATABASE_PASSWORD
  description: Password for the database user.

- name: MQTT_HOST
  description: Hostname for the mqtt broker.

- name: MQTT_PORT
  description: Port for the mqtt broker.

- name: MQTT_USER
  description: User for the mqtt broker.

- name: MQTT_PASSWORD
  description: Password for the mqtt broker.

- name: MQTT_ROOT_CERT
  description: Root Certificate for the mqtt broker.

- name: MQTT_CLIENT_CERT
  description: Client certificate to access the mqtt broker.

- name: MQTT_CLIENT_KEY
  description: Client private key to access the mqtt broker.

- name: AGENT_TOPIC
  description: "the topic of agent"

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: maestro-rds
  stringData:
    db.host: ${DATABASE_HOST}
    db.port: ${DATABASE_PORT}
    db.name: ${DATABASE_NAME}
    db.user: ${DATABASE_USER}
    db.password: ${DATABASE_PASSWORD}

- apiVersion: v1
  kind: Secret
  metadata:
    name: maestro-mqtt
  stringData:
    config.yaml: |
      brokerHost: ${MQTT_HOST}:${MQTT_PORT}
      username: ${MQTT_USER}
      password: ${MQTT_PASSWORD}
      caFile: ${MQTT_ROOT_CERT}
      clientCertFile: ${MQTT_CLIENT_CERT}
      clientKeyFile: ${MQTT_CLIENT_KEY}
      topics:
        sourceEvents: sources/maestro/consumers/+/sourceevents
        agentEvents: ${AGENT_TOPIC}
