---
kind: Template
apiVersion: v1
metadata:
  name: maestro-service
  annotations:
    openshift.io/display-name: maestro
    description: Example Service API for the Unified Hybrid Cloud deployment
    tags: golang,uhc,service-delivery
    iconClass: icon-shadowman
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://gitlab.cee.redhat.com/service/
labels:
  template: maestro
parameters:

- name: ENVIRONMENT
  displayName: Environment
  description: Which Account Manager environment to use for this deployment
  value: production

- name: IMAGE_REGISTRY
  displayName: Image Registry
  required: true

- name: IMAGE_REPOSITORY
  displayName: Image Repository
  required: true

- name: VERSION
  displayName: Image version
  value: latest

- name: IMAGE_TAG
  displayName: Image tag
  value: latest

- name: CENTOS_IMAGE_REPOSITORY
  displayName: Image Repository
  required: true
  value: centos

- name: CENTOS_IMAGE_TAG
  displayName: Image tag
  value: "7"

- name: GLOG_V
  displayName: GLOG V Level
  description: Log verbosity level
  value: "10"

- name: MEMORY_REQUEST
  description: Memory request for the API pods.
  value: "512Mi"

- name: MEMORY_LIMIT
  description: Memory limit for the API pods.
  value: "1Gi"

- name: CPU_REQUEST
  description: CPU request for the API pods.
  value: "200m"

- name: CPU_LIMIT
  description: CPU limit for the API pods.
  value: "1"

- name: JWKS_URL
  displayName: JWK Token Certificate URL

- name: JWKS_CA
  displayName: JWK Token Certificate CA

- name: OCM_BASE_URL
  displayName: OCM API Base URL
  description: Base path for all OCM APIs

- name: OCM_DEBUG
  displayName: OCM API Debug mode
  description: Debug mode for OCM API client
  value: "false"

- name: REPLICAS
  description: Number of replicas of the service to run.
  value: "1"

- name: ENABLE_JWT
  displayName: Enable JWT
  description: Enable JWT authentication validation
  value: "true"

- name: ENABLE_HTTPS
  displayName: Enable HTTPS
  description: Enable HTTPS rather than HTTP
  value: "true"

- name: HTTP_SERVER_BINDADDRESS
  displayName: HTTP Server Bindaddress
  description: HTTP server bind adddress
  value: :8000

- name: GRPC_SERVER_BINDADDRESS
  displayName: gRPC Server Bindaddress
  description: gRPC server bind adddress
  value: :8090

- name: METRICS_SERVER_BINDADDRESS
  displayName: Metrics Server Bindaddress
  description: Metrics server bind adddress
  value: :8080

- name: HEALTH_CHECK_SERVER_BINDADDRESS
  displayName: Health check Server Bindaddress
  description: Health check server bind adddress
  value: :8083

- name: HTTP_SERVER_HOSTNAME
  displayName: HTTP Server Hostname
  description: Server's public hostname
  value: ""

- name: GRPC_SERVER_HOSTNAME
  displayName: gRPC Server Hostname
  description: gRPC Server's public hostname
  value: ""

- name: ENABLE_AUTHZ
  displayName: Enable Authz
  description: Enable Authorization on endpoints, should only be disabled for debug
  value: "true"

- name: DB_MAX_OPEN_CONNS
  displayName: Maximum Open Database Connections
  description: Maximum number of open database connections per pod
  value: "50"

- name: DB_SSLMODE
  displayName: DB SSLmode
  description: Database ssl mode (disable | require | verify-ca | verify-full)
  value: "disable"

- name: ENABLE_DB_DEBUG
  displayName: Enable DB Debug
  description: framework's debug mode
  value: "false"

- name: ENABLE_METRICS_HTTPS
  displayName: Enable Metrics HTTPS
  description: Enable HTTPS for metrics server
  value: "false"

- name: ENABLE_OCM_MOCK
  displayName: Enable OCM Mock
  description: Enable mock uhc client
  value: "false"

- name: HTTP_READ_TIMEOUT
  displayName: HTTP Read Timeout
  description: HTTP server read timeout
  value: 5s

- name: HTTP_WRITE_TIMEOUT
  displayName: HTTP Write Timeout
  description: HTTP server write timeout
  value: 30s

- name: LABEL_METRICS_INCLUSION_DURATION
  displayName: Label metrics inclusion duration
  description: A cluster's last telemetry date needs be within in this duration in order to have labels collected
  value: "168h"

- name: ENABLE_SENTRY
  displayName: Enable Sentry Error Reporting
  value: "false"

- name: SENTRY_URL
  displayName: Sentry base URL
  description: Base URL (without https://) of sentry server
  value: "glitchtip.devshift.net"

- name: SENTRY_PROJECT
  displayName: Sentry Project ID
  value: "53"

- name: ENABLE_SENTRY_DEBUG
  displayName: Enable Sentry Debug Logging
  value: "false"

- name: SENTRY_TIMEOUT
  displayName: Sentry Timeout
  description: Timeout for all Sentry operations
  value: "5s"

objects:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: maestro
      labels:
        app: maestro

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: maestro
      labels:
        app: maestro
    spec:
      selector:
        matchLabels:
          app: maestro
      replicas: ${{REPLICAS}}
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: maestro
        spec:
          serviceAccountName: maestro
          volumes:
          - name: tls
            secret:
              secretName: maestro-tls
          - name: service
            secret:
              secretName: maestro
          - name: rds
            secret:
              secretName: maestro-rds
          - name: mqtt
            secret:
              secretName: maestro-mqtt
          - name: authentication
            configMap:
              name: authentication
          initContainers:
          - name: migration
            image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: service
              mountPath: /secrets/service
            - name: rds
              mountPath: /secrets/rds
            command:
            - /usr/local/bin/maestro
            - migration
            - --db-host-file=/secrets/rds/db.host
            - --db-port-file=/secrets/rds/db.port
            - --db-user-file=/secrets/rds/db.user
            - --db-password-file=/secrets/rds/db.password
            - --db-name-file=/secrets/rds/db.name
            - --alsologtostderr
            - -v=${GLOG_V}
          containers:
          - name: service
            image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: tls
              mountPath: /secrets/tls
            - name: service
              mountPath: /secrets/service
            - name: rds
              mountPath: /secrets/rds
            - name: mqtt
              mountPath: /secrets/mqtt
            - name: authentication
              mountPath: /configs/authentication
            env:
              - name: "AMS_ENV"
                value: "${ENVIRONMENT}"
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            command:
            - /usr/local/bin/maestro
            - server
            - --client-id=maestro-$(POD_NAME)
            - --db-host-file=/secrets/rds/db.host
            - --db-port-file=/secrets/rds/db.port
            - --db-user-file=/secrets/rds/db.user
            - --db-password-file=/secrets/rds/db.password
            - --db-name-file=/secrets/rds/db.name
            - --mqtt-config-file=/secrets/mqtt/config.yaml
            - --enable-ocm-mock=${ENABLE_OCM_MOCK}
            - --ocm-client-id-file=/secrets/service/ocm-service.clientId
            - --ocm-client-secret-file=/secrets/service/ocm-service.clientSecret
            - --ocm-base-url=${OCM_BASE_URL}
            - --ocm-debug=${OCM_DEBUG}
            - --https-cert-file=/secrets/tls/tls.crt
            - --https-key-file=/secrets/tls/tls.key
            - --grpc-tls-cert-file=/secrets/tls/tls.crt
            - --grpc-tls-key-file=/secrets/tls/tls.key
            - --acl-file=/configs/authentication/acl.yml
            - --jwk-cert-file=/configs/authentication/jwks.json
            - --jwk-cert-url=${JWKS_URL}
            - --enable-jwt=${ENABLE_JWT}
            - --enable-https=${ENABLE_HTTPS}
            - --http-server-hostname=${HTTP_SERVER_HOSTNAME}
            - --http-server-bindaddress=${HTTP_SERVER_BINDADDRESS}
            - --grpc-server-hostname=${GRPC_SERVER_HOSTNAME}
            - --grpc-server-bindaddress=${GRPC_SERVER_BINDADDRESS}
            - --health-check-server-bindaddress=${HEALTH_CHECK_SERVER_BINDADDRESS}
            - --enable-health-check-https=${ENABLE_HTTPS}
            - --db-sslmode=${DB_SSLMODE}
            - --db-max-open-connections=${DB_MAX_OPEN_CONNS}
            - --enable-authz=${ENABLE_AUTHZ}
            - --enable-db-debug=${ENABLE_DB_DEBUG}
            - --enable-metrics-https=${ENABLE_METRICS_HTTPS}
            - --enable-sentry=${ENABLE_SENTRY}
            - --enable-sentry-debug=${ENABLE_SENTRY_DEBUG}
            - --sentry-url=${SENTRY_URL}
            - --sentry-project=${SENTRY_PROJECT}
            - --sentry-timeout=${SENTRY_TIMEOUT}
            - --sentry-key-file=/secrets/service/sentry.key
            - --http-read-timeout=${HTTP_READ_TIMEOUT}
            - --http-write-timeout=${HTTP_WRITE_TIMEOUT}
            - --label-metrics-inclusion-duration=${LABEL_METRICS_INCLUSION_DURATION}
            - --alsologtostderr
            - -v=${GLOG_V}
            resources:
              requests:
                cpu: ${CPU_REQUEST}
                memory: ${MEMORY_REQUEST}
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
            livenessProbe:
              httpGet:
                path: /api/maestro
                port: 8000
                scheme: HTTPS
              initialDelaySeconds: 15
              periodSeconds: 5
            readinessProbe:
              httpGet:
                path: /healthcheck
                port: 8083
                scheme: HTTPS
                httpHeaders:
                - name: User-Agent
                  value: Probe
              initialDelaySeconds: 20
              periodSeconds: 10

  - kind: Service
    apiVersion: v1
    metadata:
      name: maestro
      labels:
        app: maestro
        port: api
      annotations:
        description: Exposes and load balances the maestro pods restful api endpoint
        service.alpha.openshift.io/serving-cert-secret-name: maestro-tls
    spec:
      selector:
        app: maestro
      ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP

  - kind: Service
    apiVersion: v1
    metadata:
      name: maestro-grpc
      labels:
        app: maestro-grpc
        port: grpc
      annotations:
        description: Exposes and load balances the maestro pods grpc endpoint
        service.alpha.openshift.io/serving-cert-secret-name: maestro-tls
    spec:
      selector:
        app: maestro
      ports:
        - port: 8090
          targetPort: 8090
          protocol: TCP

  # Services for diagnostic ports (not part of main service because we
  # don't want exposing them externally through same route).
  - kind: Service
    apiVersion: v1
    metadata:
      name: maestro-metrics
      labels:
        app: maestro
        port: metrics
      annotations:
        description: Exposes and load balances the maestro pods metrics endpoint
        service.alpha.openshift.io/serving-cert-secret-name: maestro-metrics-tls
    spec:
      selector:
        app: maestro
      ports:
      - port: 8080
        targetPort: 8080
        name: metrics

  - apiVersion: v1
    kind: Service
    metadata:
      name: maestro-healthcheck
      labels:
        app: maestro
        port: healthcheck
    spec:
      selector:
        app: maestro
      ports:
      - port: 8083
        targetPort: 8083
