{
 "title": "Maestro Server",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Advisory Unlock Requests Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(advisory_lock_count[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Advisory Lock Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(advisory_lock_duration_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CloudEvents Sent Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(cloudevents_sent_total{app=\"maestro\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Advisory Unlock Requests Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(advisory_unlock_count[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CloudEvents Received Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(cloudevents_received_total{app=\"maestro\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resource Processed Rate by Action",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (action) (rate(resource_processed_total[5m]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "gRPC Server Processed Total by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (type) (rate(grpc_server_processed_total[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "REST API Inbound Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (code,method,path) (rate(rest_api_inbound_request_count[5m]))",
     "legendFormat": "{{method}} {{path}} ({{code}})"
    }
   ]
  },
  {
   "title": "REST API Inbound Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rest_api_inbound_request_duration_bucket[5m])) by(le))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}