{
 "title": "Maestro Agent",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Cloud Events Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CloudEvents Sent Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(cloudevents_sent_total{app=\"maestro-agent\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CloudEvents Received Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(cloudevents_received_total{app=\"maestro-agent\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests to APIServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(method) (rate(rest_client_requests_total{app=\"maestro-agent\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration - P75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, max by(verb, le) (rest_client_request_duration_seconds_bucket{app=\"maestro-agent\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Enqueue Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(name) (rate(workqueue_adds_total{name=\"ManifestWorkAgent\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "max by(name) (workqueue_depth{name=\"ManifestWorkAgent\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}