{
 "title": "Maestro Server",
 "description": "ARO HCP Maestro Server Component",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SLO Availability: Maestro Server",
   "type": "timeseries",
   "description": "maestro server availability where 1 is good and 0 is bad",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time(kube_deployment_status_replicas_available{deployment=\"maestro\"}[28d]) / sum_over_time(kube_deployment_spec_replicas{deployment=\"maestro\"}[28d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maestro Server REST HTTP Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Availability: Maestro Server Request Success Rate",
     "type": "timeseries",
     "description": "Measure the percentage of successful API requests (non-5xx)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum((rate(rest_api_inbound_request_count{code!~\"5..\"}[5m])))\n/\nsum((rate(rest_api_inbound_request_count{}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Latency: Maestro Server Request Latency",
     "type": "timeseries",
     "description": "Ratio of maestro server's requests taking less than 1 second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by(path,method,code) (rate(rest_api_inbound_request_duration_bucket{le=~\"^1(\\\\.0)?$\"}[5m]))\n/\nsum by(path,method,code) (rate(rest_api_inbound_request_duration_bucket{le=\"+Inf\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Maestro Server Advisory Lock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Duration: Maestro Server Advisory Lock Duration",
     "type": "timeseries",
     "description": "Ratio of maestro server's advisory lock with duration less than 0.5 second",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(advisory_lock_duration_bucket{le=~\"^0(\\\\.5)?$\"}[5m]))\n/\nsum(rate(advisory_lock_duration_bucket{le=\"+Inf\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Available: Maestro Server Advisory Lock Release Ratio",
     "type": "timeseries",
     "description": "Ratio of maestro server's advisory lock release to advisory lock acquisition",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(advisory_unlock_count{status=\"OK\"}[5m]))\n/\nsum(rate(advisory_lock_count{status=\"OK\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Maestro gRPC Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Duration: Maestro gRPC Server Call Duration",
     "type": "timeseries",
     "description": "Ratio of maestro gRPC server call duration less than 0.5 second",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_processed_duration_seconds_bucket{le=~\"^0(\\\\.5)?$\"}[5m]))\n/\nsum(rate(grpc_server_processed_duration_seconds_bucket{le=\"+Inf\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Maestro Server Spec Recync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maestro Server Spec Resync Duration",
     "type": "timeseries",
     "description": "Ratio of maestro server spec resync call takes less than 10 seconds",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(rate(resources_spec_resync_duration_seconds_bucket{le=~\"^10(\\\\.0)?$\"}[5m]))\n/\nsum(rate(resources_spec_resync_duration_seconds_bucket{le=\"+Inf\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}