{
 "title": "Maestro Agent",
 "description": "ARO HCP Maestro Agent Component",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SLO Availability: Maestro Agent",
   "type": "timeseries",
   "description": "maestro agent availability where 1 is good and 0 is bad",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time(kube_deployment_status_replicas_available{deployment=\"maestro-agent\"}[28d]) / sum_over_time(kube_deployment_spec_replicas{deployment=\"maestro-agent\"}[28d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maestro Agent REST Client Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Availability: Maestro Agent Rest Client Request Success Rate",
     "type": "timeseries",
     "description": "Measure the percentage of successful rest client requests (non-5xx)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum((rate(rest_client_requests_total{code!~\"5..\"}[5m])))\n/\nsum((rate(rest_client_requests_total{}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Latency: Maestro Agent Rest Client Request Latency",
     "type": "timeseries",
     "description": "Ratio of maestro agent's rest client requests taking less than 0.5 second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by(host,verb) (rate(rest_client_request_duration_seconds_bucket{le=~\"^0(\\\\.5)?$\"}[5m]))\n/\nsum by(host,verb) (rate(rest_client_request_duration_seconds_bucket{le=\"+Inf\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Maestro Agent Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SLO Duration: Maestro Agent Work Queue Dequeue Duration",
     "type": "timeseries",
     "description": "Ratio of maestro agent workqueue dequeue in less than 1 second",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(workqueue_queue_duration_seconds_bucket{le=~\"^1(\\\\.0)?$\"}[5m]))\n/\nsum(rate(workqueue_queue_duration_seconds_bucket{le=\"+Inf\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Duration: Maestro Agent Work Queue Item Process Duration",
     "type": "timeseries",
     "description": "Ratio of maestro agent workqueue item processed in less than 1 second",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(workqueue_work_duration_seconds_bucket{le=~\"^1(\\\\.0)?$\"}[5m]))\n/\nsum(rate(workqueue_work_duration_seconds_bucket{le=\"+Inf\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLO Available: Maestro Agent Work Queue Retry Ratio",
     "type": "timeseries",
     "description": "Ratio of maestro agent retry attempt to add totals",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(workqueue_retries_total{}[5m]))\n/\nsum(rate(workqueue_adds_total{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}