kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: maestro-integration-test
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
    - description: 'Expected output'
      name: EXPECTED_OUTPUT
      default: ""
      type: string
  tasks:
    - name: integration-test
      description: Set up DB, run integration tests, and read results
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: EXPECTED_OUTPUT
          value: $(params.EXPECTED_OUTPUT)
      taskSpec:
        params:
        - name: SNAPSHOT
        - name: NAMESPACE
        - name: EXPECTED_OUTPUT
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "6Gi"
              cpu: "4"
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: NAMESPACE
            value: $(params.NAMESPACE)
          - name: EXPECTED_OUTPUT
            value: $(params.EXPECTED_OUTPUT)
          script: |
            # Install Deps
            dnf -y install jq git make

            # Install golang with a given version
            export GOVERSION=1.25.0
            curl -O -J https://dl.google.com/go/go$GOVERSION.linux-amd64.tar.gz
            rm -rf /usr/local/go && tar -C /usr/local -xzf go$GOVERSION.linux-amd64.tar.gz

            # Runtime Env Config
            export PATH=$PATH:/usr/local/bin:/usr/local/go/bin:$HOME/go/bin
            export GOPATH=$HOME/go

            go install gotest.tools/gotestsum@latest  

            # Set Vars
            TARGET_COMPONENT_NAME="maestro"
            REPO_URL=$(echo $SNAPSHOT | jq -r '.components[] | select(.name == "maestro").source.git.url')
            REPO_COMMIT=$(echo $SNAPSHOT | jq -r '.components[] | select(.name == "maestro").source.git.revision')
            mqtt_test_output_file=${PWD}/mqtt_test_output.json
            pubsub_test_output_file=${PWD}/pubsub_test_output.json
            grpc_test_output_file=${PWD}/grpc_test_output.json

            # Log Vars for Tracibility
            echo "REPO_URL: $REPO_URL"
            echo "TARGET_COMPONENT_NAME: $TARGET_COMPONENT_NAME"
            echo "REPO_COMMIT: $REPO_COMMIT"
            echo "SNAPSHOT: $(echo $SNAPSHOT | jq)"

            # Clone Repo and checkout at snapshot commit
            git clone $REPO_URL $TARGET_COMPONENT_NAME
            cd $TARGET_COMPONENT_NAME
            git config --local --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'
            git fetch origin
            git checkout $REPO_COMMIT

            # Wait for the DB sidecar to be ready
            echo "[INFO] Waiting for database to be ready for connection"
            timeout 5m bash -c 'until echo > /dev/tcp/localhost/5432; do sleep 2s; done'

            # Generate mqtt config file
            echo '{"brokerHost":"localhost:1883","username":"","password":"","topics":{"sourceEvents":"sources/maestro/consumers/+/sourceevents","agentEvents":"sources/maestro/consumers/+/agentevents"}}' > secrets/mqtt.config

            # Generate pubsub config file
            echo '{"projectID":"maestro-test","endpoint":"localhost:8085","insecure":true,"topics":{"sourceEvents":"projects/maestro-test/topics/sourceevents","sourceBroadcast":"projects/maestro-test/topics/sourcebroadcast"},"subscriptions":{"agentEvents":"projects/maestro-test/subscriptions/agentevents-maestro","agentBroadcast":"projects/maestro-test/subscriptions/agentbroadcast-maestro"}}' > secrets/pubsub.config

            # Generate db.password
            echo 'foobar-bizz-buzz' > secrets/db.password

            # Wait for the pubsub emulator to be ready
            echo "[INFO] Waiting for pubsub emulator to be ready for connection"
            timeout 5m bash -c 'until curl -s http://localhost:8085 > /dev/null 2>&1; do sleep 2s; done'

            # Initialize pubsub topics and subscriptions
            export PUBSUB_EMULATOR_HOST=localhost:8085
            export PUBSUB_PROJECT_ID=maestro-test
            bash hack/init-pubsub-emulator.sh

            # Run integration tests with JSON output
            make test-integration \
              mqtt_integration_test_json_output="$mqtt_test_output_file" \
              pubsub_integration_test_json_output="$pubsub_test_output_file" \
              grpc_integration_test_json_output="$grpc_test_output_file"

            # Read, process, and write output in accepted format
            # Formatting docs: https://redhat-appstudio.github.io/book/ADR/0030-tekton-results-naming-convention.html#test_output-schema-validation
            # Combine results from all three broker tests
            MQTT_FAILURES=$(cat $mqtt_test_output_file | jq 'select(.Action == "fail")' | jq -r --slurp 'length')
            MQTT_SUCCESSES=$(cat $mqtt_test_output_file | jq 'select(.Action == "pass")' | jq -r --slurp 'length')
            PUBSUB_FAILURES=$(cat $pubsub_test_output_file | jq 'select(.Action == "fail")' | jq -r --slurp 'length')
            PUBSUB_SUCCESSES=$(cat $pubsub_test_output_file | jq 'select(.Action == "pass")' | jq -r --slurp 'length')
            GRPC_FAILURES=$(cat $grpc_test_output_file | jq 'select(.Action == "fail")' | jq -r --slurp 'length')
            GRPC_SUCCESSES=$(cat $grpc_test_output_file | jq 'select(.Action == "pass")' | jq -r --slurp 'length')
            FAILURES=$((MQTT_FAILURES + PUBSUB_FAILURES + GRPC_FAILURES))
            SUCCESSES=$((MQTT_SUCCESSES + PUBSUB_SUCCESSES + GRPC_SUCCESSES))
            # Hard-code warnings
            WARNINGS=0
            RESULT="$(if [[ $FAILURES == 0 ]]; then echo "SUCCESS"; else echo "FAILURE"; fi)"
            # TODO: Switch to rfc-3339 when RHTAP changes the schema
            # TIMESTAMP="$(date --rfc-3339=seconds)"
            TIMESTAMP="$(date +%s)"
            TEST_OUTPUT=$(jq -r --null-input \
              --arg failures $FAILURES \
              --arg successes $SUCCESSES \
              --arg warnings $WARNINGS \
              --arg result "$RESULT" \
              --arg timestamp "$TIMESTAMP" \
              '{"result": $result, "successes": $successes|tonumber, "failures": $failures|tonumber, "warnings": $warnings|tonumber, "timestamp": $timestamp}' \
            )
            echo -n "$TEST_OUTPUT" | tee $(results.TEST_OUTPUT.path)
        sidecars:
          - image: quay.io/maestro/postgres:17.2
            name: database-test
            env:
            - name: PGDATA
              value: /work/data
            - name: POSTGRES_DB
              value: maestro
            - name: POSTGRES_PASSWORD
              value: foobar-bizz-buzz
            - name: POSTGRES_USER
              value: maestro
            volumeMounts:
              - mountPath: /work
                name: pgdata
          - image: quay.io/maestro/eclipse-mosquitto:2.0.20
            name: mqtt-test
            volumeMounts:
              - mountPath: /mosquitto/data
                name: mqttdata
          - image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
            name: pubsub-test
            command:
              - gcloud
              - beta
              - emulators
              - pubsub
              - start
              - --host-port=0.0.0.0:8085
              - --project=maestro-test
        volumes:
          - name: pgdata
            emptyDir: {}
          - name: mqttdata
            emptyDir: {}
