{
 "title": "Maestro Server",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Advisory Lock Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(advisory_lock_count)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Advisory Lock Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(advisory_lock_duration_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CloudEvents Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cloudevents_sent_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Advisory Unlock Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(advisory_unlock_count)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "CloudEvents Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudevents_received_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Resource Processed Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (action) (rate(resource_processed_total[5m]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "gRPC Server Processed Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (type) (rate(grpc_server_processed_total[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "REST API Inbound Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (code,method,path) (rate(rest_api_inbound_request_count[5m]))",
     "legendFormat": "{{method}} {{path}} ({{code}})"
    }
   ]
  },
  {
   "title": "REST API Inbound Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(rest_api_inbound_request_duration_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}